### ISSUE TITLE
Feedback Score

### ISSUE THREAD

**Issue by tjoye20** [sdennehy311/Sean-Dennehy-Calculating-Churn-Rates-Capstone-Project#1]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 3: Query Formatting
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4 - Exceeds Expectations

 ### Overall Score: 16/16
Hi Sean, you pretty much crushed this project. It's clear you have a good understanding of SQL as well as the underlying concepts the queries were analyzing. Great job with the queries and formatting, as they were easy to read and follow.

**Comment by sdennehy311** [comment]
Thanks for the review, appreciate the feedback.  The course was fun and challenging!
